---
- name: register playbook
  hosts: all
  tasks:
   - name : Run the following command
     command: uptime
     register: server_uptime

   - name: Show server uptime
     debug:
       var: server_uptime

   - name: Display server uptime
     debug:
       msg: "{{ server_uptime.stdout }}" 
