---
- name: Configure SSH, here i am using blockinline module to insert multiple lines of text into the configuration file and we use lineinfile module for single line.
  hosts: all
  tasks:
    - name: Edit configuration file
      blockinfile:
        dest: /etc/ssh/sshd_config
        block: |
          MaxAuthTries 4
          X11forwarding no
          Banner /etc/motd
      notify: restart ssh
  handlers:
    - name: restart ssh
      service:
         name: sshd
         state: restarted
