---
- name: This example demonstartes the usage of lineinfile module
  hosts: all
  tasks:
    - name: create a file 
      file:
        dest: /tmp/lineinfile.txt
        state: touch
        mode: 0755
        owner: ansible
      notify: Remove the file

    - name: add below line to the file
      lineinfile:
        dest: /tmp/lineinfile.txt
        line: This is an example file for lineinfile
      notify: remove the line
  handlers:
    - name: remove the line
      lineinfile:
        dest: /tmp/lineinfile.txt
        regexp: This is an example file for lineinfile  #Regular expression to match the line to remove
        state: absent
    - name: Remove the file
      file:
        dest: /tmp/lineinfile.txt
        state: absent
