---
- name: Accessing vaults inside playbook
  hosts: localhost
  vars_files:
     - websecrets.yml
     - dbsecrets.yml
  tasks:
    - name: Show websecrets
      debug:
        msg: "{{ secret }}"

    - name: Show dbsecrets
      debug:
        msg: "{{ dbsecret }}"
