---
- name: This is example of using dictionaries in variables
  hosts: all
  vars:
   users:
     bob:
      username: bob
      uid: 1122
      group: wheel
      shell: /bin/bash

     lisa:
      username: lisa
      uid: 2233
      group: wheel
      shell: /bin/bash
  tasks:
   - name: Print the group and shell of the user bob
     debug:
       msg: The group of the {{ users['bob']['username'] }} is {{ users['bob']['group'] }} and the shell is {{ users['bob']['shell'] }}
# This is one way of accessing elements from dictionary
#
   - name: Print the group and shell of the user bob
     debug:
       msg: The group of the {{ users.lisa.username }} is {{ users.lisa.group }} and the shell is {{ users.lisa.shell }}
       # This is the another way of accessing elements from dictionary
