--- 
- name: This example demonstrates the use of variable files using keyword
  hosts: all
  vars_files:
       - variablefile.yml
  tasks:
    - name : print the port number
      debug: 
        msg: The port numbers are {{ port_num }} and the portnumber {{ port_num[1] }} is used for SSH access.
    - name: list out the users
      debug: 
        msg: The users we have in our machine are {{ users }}
