---
- name: Get userinput for the varibales at the runtime
  hosts: all
  vars_prompt: 
     - name: username
       prompt: what's your username
       private: no  
       # private is no, so that you can see your input on your screen as you type it, by default it's hidden
  tasks:
    - name: greet the user
      debug:
        msg: Hello {{ username }}
