---
- name: This a playbook to understand variables
  hosts: all
  vars:
   - fav_color: black
     fav_actor: Prabhas
  tasks:
   - name: Print your favourite actor and favourite colour
     debug:
       msg: |
        {{ fav_color }} is my favourite color
        My favourite actor is {{ fav_actor }}
        this is my first variable playbook

   - name: Print your favourite actor and favourite colour
     debug:
       msg: >
        {{ fav_color }} is my favourite color
        My favourite actor is {{ fav_actor }}
        this is my first variable playbook

   - name: Print the favourite colour
     debug:
       msg: "{{ fav_color }} is my favorite color"

   - name: Print favourite actor
     debug:
       msg: my favourite actor is {{ fav_actor }}
