   - name: checking for git
     command: git --version
     ignore_errors: yes
     register: git_version

   - name: show git version
     debug:
      var: git_version

   - name: remove git
     package: 
       name: git
       state: absent
     when: "'git version ' in git_version.stdout"
 
