---
- name: first play
  hosts: all
  tasks:
   - name: install tmux
     package:
       name: tmux
       state: present

   - name: create archive file
     archive:
       path: /var/log
       dest: /tmp/log.tar.gz
       format: gz
- name: second play
  hosts: localhost
  tasks:
   - name: install git
     yum:
      name: git
      state: present
