---
- name: deploy vsftpd
  hosts: all
  tasks:
   - name: install vsftpd
     yum:
       name: vsftpd
       state: present

   - name: enable vsftpd
     service:
       name: vsftpd
       enabled: True

   - name: create readme
     copy:
       content: "Hi this is vsftpd file"
       dest: /var/ftp/pub/README
       force: no
       mode: 0444
