---
- name: The following task will run only if car variable is defined
  hosts: localhost
  vars:
    car: mercedes
  tasks:
    - name: Run the following task if car variables is defined
      debug:
        msg: we will go to a trip in {{ car }}
      when: car is defined

    - name: Run the follwing task if car is not defined
      debug:
        msg: We will go to a trip by train
      when: car is not defined
