---
- name: Using when with registers
  hosts: all
  tasks:
    - name: Show the user on the server
      command: cat /etc/passwd
      register: users

    - name: Detect the user ansible
      debug:
        msg: ansible user is present on the {{ inventory_hostname }}
      when: users.stdout.find( 'ansible' ) != -1
