---
- name: This example demonstartes the usage of jinja2templates with variables
  hosts: all
  vars:
    webserver_message: I am running to the line
  tasks:
   - name: restart the apache
     service:
         name: httpd
         state: restarted

   - name: Accessing variables in Jinja2
     template:
        src: index.j2
        dest: /var/www/html/index.html
