---
- name: you can use the if conditional statement in jinja2 for testing various conditions
  hosts: all
  tasks:
    - name: Display selinux status
      debug:
        msg: "{{ ansible_facts['selinux']['status'] }}"

    - name: create selinux.out using jinja2
      template:
        src: selinux.j2
        dest: /tmp/selinux.out
