---
- name: This is lab3 playbook
  hosts: all
  tasks: 
   - name: install nmap
     package: 
       name: nmap
       state: present

   - name: check version of nmap
     command: nmap --version
     register: nmap_output

   - name: show the version of nmap
     debug:
       var: nmap_output

   - name: Create a bzip2 compressed archive
     archive:
       path: /home
       dest: /tmp/home.tar.gz
       format: gz
       
