---
- name: Reuisng of tasks and playbooks
  hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: rebooting server
      reboot:
        msg: server is rebooting

- name: starting the httpd services
  import_playbook: starthttpd.yml
