---
- name: This Example is used to demonstrate changed_when keyword and detailed information about when handlers will run. To understand clearly check this playbook and next playbook control_change.yml as well.
  hosts: localhost
  tasks:
    - name: Run the date command
      command: date
      notify: testing handler

    - name: Run the uptime command
      command: uptime
  handlers:
    - name: testing handler
      debug:
        msg: This handler will handle the dates
