---
- name: Using when with multiple conditions
  hosts: all
  tasks:
    - name: Reboot the server
      reboot:
        msg: "server is rebooting...."
      when: >
        ansible_distribution == "RedHat" and
        ansible_distribution_major_version == "8.6"

    - name: Reboot the server
      reboot:
        msg: "server is rebooting...."
      when: >
        ansible_distribution == "Amazon" and
        ansible_distribution_major_version == "2"

