---
- name: using include-vars file we can dynamically load the variables at the time of running playbook
  hosts: all
  tasks:
   - name: Load the variables
     include_vars: variablefile.yml

   - name: print the portnumber for SSh
     debug:
       msg: The portnumber for SSH is {{ port_num[1] }}
